name: Enviar Resumo Diário da Agenda para o Slack

on:
  schedule:
    # O agendamento (cron) do GitHub Actions usa o fuso horário UTC.
    # O horário de Brasília (BRT) é UTC-3.

    # Roda às 10:30, 14:30 e 20:30 UTC de Segunda a Sexta.
    # Corresponde a 07:30, 11:30 e 17:30 no horário de Brasília.
    - cron: '30 10,14 * * 1-5'

    # Roda às 17:00 UTC de Segunda a Sexta.
    # Corresponde a 14:00 no horário de Brasília.
    - cron: '00 17,20 * * 1-5'
  workflow_dispatch:

jobs:
  enviar-resumo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Executar script para enviar resumo
        env:
          API_COOKIE: ${{ secrets.API_COOKIE }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          AMEI_USERNAME: ${{ secrets.AMEI_USERNAME }}
          AMEI_PASSWORD: ${{ secrets.AMEI_PASSWORD }}
        run: python app.py